import { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, Users, Sparkles, Mic, Clock, Shield, Globe, CheckCircle } from 'lucide-react'

export const metadata: Metadata = {
  title: 'AI Actors - 300+ Realistic Digital Actors for Videos | blacktools.ai',
  description: 'Access 300+ hyper-realistic AI actors for your video content. All demographics, styles, and languages. No hiring, no scheduling—instant AI talent. Try free.',
  keywords: 'AI actors, digital actors, AI talent, virtual actors, AI spokesperson, AI video actors',
  alternates: {
    canonical: 'https://blacktools.ai/ai-actors',
  },
  openGraph: {
    title: 'AI Actors - 300+ Realistic Digital Actors for Videos',
    description: 'Access 300+ hyper-realistic AI actors for your video content. All demographics, styles, and languages.',
    url: 'https://blacktools.ai/ai-actors',
    siteName: 'blacktools.ai',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'AI Actors - 300+ Realistic Digital Actors for Videos',
    description: 'Access 300+ hyper-realistic AI actors for your video content.',
  },
  robots: {
    index: true,
    follow: true,
  },
}

const demographics = [
  { label: 'Ages', items: ['Gen Z', 'Millennials', 'Gen X', 'Boomers'] },
  { label: 'Ethnicities', items: ['Global diversity representing all markets'] },
  { label: 'Genders', items: ['Male', 'Female', 'Non-binary options'] },
]

const styles = [
  'Casual Influencer',
  'Business Professional',
  'Friendly Expert',
  'Energetic Presenter',
  'Calm Authority',
]

const features = [
  {
    icon: Sparkles,
    title: 'Natural Performance',
    description: 'AI actors display genuine expressions—they can look surprised, excited, serious, or friendly based on your script.',
  },
  {
    icon: Mic,
    title: 'Perfect Lip Sync',
    description: 'Industry-leading synchronization in 30+ languages. Actors speak naturally in any language without dubbing artifacts.',
  },
  {
    icon: Clock,
    title: 'Consistent Availability',
    description: 'Unlike real actors, AI actors are always available. Create content 24/7 without scheduling conflicts.',
  },
  {
    icon: Users,
    title: 'Unlimited Takes',
    description: 'Regenerate as many times as needed. Tweak the script, adjust the tone—no additional talent fees.',
  },
  {
    icon: Shield,
    title: 'Commercial Rights',
    description: 'Full commercial usage rights for all AI actors. Use in ads, websites, social media, anywhere.',
  },
]

const useCases = [
  { title: 'Ad Campaigns', description: 'Consistent spokesperson across all creatives' },
  { title: 'Testimonials', description: 'Diverse faces representing customer base' },
  { title: 'Training Videos', description: 'Professional presenters for internal content' },
  { title: 'Social Media', description: 'Fresh content with different personalities' },
  { title: 'Multilingual', description: 'Same actor, multiple languages' },
]

const faqs = [
  {
    question: 'What are AI actors?',
    answer: 'AI actors are digital performers generated by artificial intelligence. They can speak any script, express emotions, and appear in videos without the need for real human talent. blacktools.ai offers 300+ AI actors covering diverse demographics and styles.',
  },
  {
    question: 'How realistic are AI actors?',
    answer: 'Very realistic. blacktools.ai AI actors feature natural facial expressions, accurate lip synchronization, and human-like movements. In typical viewing conditions (social media, ads), most viewers perceive them as real people.',
  },
  {
    question: 'Can AI actors speak different languages?',
    answer: 'Yes. Every AI actor on blacktools.ai can speak 30+ languages with native-quality lip sync. The same actor can deliver your message in English, Spanish, Japanese, or any supported language.',
  },
  {
    question: 'Do I own the rights to videos with AI actors?',
    answer: 'Yes. All blacktools.ai plans include full commercial usage rights. You can use videos featuring our AI actors in ads, on your website, social media, or any commercial purpose without additional licensing.',
  },
  {
    question: 'Can I create a custom AI actor?',
    answer: "Yes. Premium plans on blacktools.ai include custom avatar creation. You can create a unique AI actor for your brand's exclusive use—your own digital spokesperson.",
  },
]

export default function AIActorsPage() {
  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map((faq) => ({
      '@type': 'Question',
      name: faq.question,
      acceptedAnswer: {
        '@type': 'Answer',
        text: faq.answer,
      },
    })),
  }

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Home',
        item: 'https://blacktools.ai',
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: 'AI Actors',
        item: 'https://blacktools.ai/ai-actors',
      },
    ],
  }

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />

      <div className="min-h-screen bg-[#050505] text-white">
        {/* Header */}
        <header className="border-b border-white/5">
          <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
            <Link href="/" className="text-xl font-bold">
              blacktools<span className="text-neutral-500">.ai</span>
            </Link>
            <nav className="hidden md:flex items-center gap-6 text-sm text-neutral-400">
              <Link href="/ai-ugc-generator" className="hover:text-white transition-colors">AI UGC</Link>
              <Link href="/ai-avatar-creator" className="hover:text-white transition-colors">AI Avatars</Link>
              <Link href="/ai-actors" className="text-white">AI Actors</Link>
              <Link href="/pricing" className="hover:text-white transition-colors">Pricing</Link>
            </nav>
            <Link
              href="/signup"
              className="px-4 py-2 bg-white text-black rounded-lg text-sm font-medium hover:bg-neutral-200 transition-colors"
            >
              Start Free Trial
            </Link>
          </div>
        </header>

        {/* Hero */}
        <section className="py-20 px-6">
          <div className="max-w-4xl mx-auto text-center">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-sm text-neutral-400 mb-6">
              <Users className="w-4 h-4 text-indigo-500" />
              300+ Digital Talent Available
            </div>
            <h1 className="text-4xl sm:text-6xl font-medium tracking-tight mb-6">
              AI Actors
            </h1>
            <p className="text-xl text-neutral-400 mb-4">
              300+ Digital Actors Ready to Work
            </p>
            <p className="text-neutral-500 max-w-2xl mx-auto mb-8">
              Access a diverse library of hyper-realistic AI actors. No auditions, no contracts, no scheduling—just instant talent for any video project.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link
                href="/signup"
                className="px-8 py-3 bg-white text-black rounded-lg font-medium hover:bg-neutral-200 transition-colors flex items-center gap-2"
              >
                Browse AI Actors
                <ArrowRight className="w-4 h-4" />
              </Link>
              <Link
                href="#library"
                className="px-8 py-3 border border-white/20 rounded-lg font-medium hover:bg-white/5 transition-colors"
              >
                Create Video
              </Link>
            </div>
          </div>
        </section>

        {/* What are AI Actors */}
        <section className="py-20 px-6 border-t border-white/5">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-medium mb-6">What Are AI Actors?</h2>
            <div className="prose prose-invert prose-neutral max-w-none">
              <p className="text-neutral-400 text-lg leading-relaxed mb-6">
                <strong className="text-white">AI Actors</strong> are digital performers created using artificial intelligence. They can speak, express emotions, and deliver content that looks remarkably human. Unlike stock footage or basic avatars, AI actors are fully customizable and can say anything you need.
              </p>
              <p className="text-neutral-400 leading-relaxed">
                blacktools.ai offers <strong className="text-white">300+ AI actors</strong> covering every demographic, style, and personality you might need.
              </p>
            </div>
          </div>
        </section>

        {/* Actor Library */}
        <section id="library" className="py-20 px-6 border-t border-white/5">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-medium mb-12 text-center">Our AI Actor Library</h2>

            <div className="grid md:grid-cols-3 gap-8 mb-12">
              <div>
                <h3 className="font-medium mb-4 text-indigo-400">Diverse Demographics</h3>
                {demographics.map((demo) => (
                  <div key={demo.label} className="mb-4">
                    <p className="text-sm font-medium mb-1">{demo.label}</p>
                    <ul className="text-sm text-neutral-400">
                      {demo.items.map((item, i) => (
                        <li key={i}>{item}</li>
                      ))}
                    </ul>
                  </div>
                ))}
              </div>
              <div>
                <h3 className="font-medium mb-4 text-indigo-400">Professional Styles</h3>
                <ul className="space-y-2">
                  {styles.map((style) => (
                    <li key={style} className="text-sm text-neutral-400 flex items-center gap-2">
                      <CheckCircle className="w-4 h-4 text-indigo-400" />
                      {style}
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <h3 className="font-medium mb-4 text-indigo-400">Appearance Options</h3>
                <ul className="space-y-2 text-sm text-neutral-400">
                  <li className="flex items-center gap-2">
                    <CheckCircle className="w-4 h-4 text-indigo-400" />
                    Various outfits and settings
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckCircle className="w-4 h-4 text-indigo-400" />
                    Different backgrounds
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckCircle className="w-4 h-4 text-indigo-400" />
                    Multiple angles and framings
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* Features */}
        <section className="py-20 px-6 border-t border-white/5">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-medium mb-12 text-center">Features</h2>
            <div className="grid sm:grid-cols-2 gap-8">
              {features.map((feature) => (
                <div key={feature.title} className="flex gap-4">
                  <feature.icon className="w-6 h-6 text-indigo-400 flex-shrink-0 mt-1" />
                  <div>
                    <h3 className="font-medium mb-2">{feature.title}</h3>
                    <p className="text-neutral-400 text-sm leading-relaxed">{feature.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Use Cases */}
        <section className="py-20 px-6 border-t border-white/5">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-medium mb-8 text-center">Use Cases</h2>
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {useCases.map((useCase) => (
                <div key={useCase.title} className="p-4 rounded-lg bg-white/[0.02] border border-white/5">
                  <h3 className="font-medium mb-1">{useCase.title}</h3>
                  <p className="text-sm text-neutral-400">{useCase.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* FAQ */}
        <section className="py-20 px-6 border-t border-white/5">
          <div className="max-w-3xl mx-auto">
            <h2 className="text-3xl font-medium mb-12 text-center">Frequently Asked Questions</h2>
            <div className="space-y-6">
              {faqs.map((faq) => (
                <div key={faq.question} className="border-b border-white/5 pb-6">
                  <h3 className="text-lg font-medium mb-3">{faq.question}</h3>
                  <p className="text-neutral-400 leading-relaxed">{faq.answer}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="py-20 px-6 border-t border-white/5">
          <div className="max-w-2xl mx-auto text-center">
            <h2 className="text-3xl font-medium mb-4">Meet Your New Digital Talent</h2>
            <p className="text-neutral-400 mb-8">300+ actors. Any demographic. Always available.</p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link
                href="/signup"
                className="px-8 py-3 bg-white text-black rounded-lg font-medium hover:bg-neutral-200 transition-colors"
              >
                Browse Actors
              </Link>
              <Link
                href="/pricing"
                className="px-8 py-3 border border-white/20 rounded-lg font-medium hover:bg-white/5 transition-colors"
              >
                View Pricing
              </Link>
            </div>
          </div>
        </section>

        {/* Footer */}
        <footer className="border-t border-white/5 py-8 px-6">
          <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4 text-sm text-neutral-500">
            <p>&copy; {new Date().getFullYear()} blacktools.ai. All rights reserved.</p>
            <div className="flex items-center gap-6">
              <Link href="/terms" className="hover:text-white transition-colors">Terms</Link>
              <Link href="/privacy" className="hover:text-white transition-colors">Privacy</Link>
            </div>
          </div>
        </footer>
      </div>
    </>
  )
}
